language: java
before_install:
- chmod +x gradlew
notifications:
  slack:
    secure: bvmBmvQDX0pAistZ8/Bxv3JDl3WQgdfM7DGJp0dBWUwWGteCfrwBIeeNfeImPiH/PKv15OAYtfdqkmGmuHHX7APEPdh3zsYhfKlUJhiFLo96k41HGOIBiNstSLKJBgzzrLxKOQoPRQf+dfC717agTRlEjXnlGkubogM/Gc4qyIVO4I5wuQ8ZPcJ3Lx9/+DfKmSWXX7xXFidoN2dWqPmgT0208Zm+5azSTe3hCaBtlK9pfa3cAUYsM0GCtFsbvU8oB/sC6HlCqA1lPJYydpGm3NvP8jQ6KE3p6GjDdWaTc2S1W734vVuq/ollU52WOd1UtQPr7561nyMkr22Rk4aUeeLvd9rJ6Rl0MRBxIpK63J5Z/oR1EAwl6arMDwPlSYrTq0DIP8LCEX4GPN2A8+a4eZthw0Fkm+X83JlA5/rlWJQaI7IQ4ziD4dO7fBcUaWlni4j6+PjXdFbkqY+kzeFcCxN6gQmkBlLHr6rhOKUfzX5lk2JoWsZFkQCDvyf0/fHghW19KAtJsWES5UAmp6Ufn0bThEkPJMYPzSPdM3qY6hByh0+ywIpxXWoZksnZvw11KiCmiNKJlh2SgWxfqkqJ/N6wGzSksulVzOyQi4Qc5PyN0HRkqp7uNqF19t9kc5hP0kqehh8l/ng5h9AUbXRrmRjiayeOKd/Pfyf/a25NGyU=
script:
- "./gradlew clean build -i --continue"
